[target.aarch64-unknown-linux-gnu.dockerfile]
file = "./Docker/Dockerfile.cross"
context = "./Docker"

[target.aarch64-unknown-linux-gnu.dockerfile.build-args]
LINKER_PACKAGE = "gcc-aarch64-linux-gnu"
RUST_TARGET_TRIPLE = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu.env]
passthrough = ["CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc"]

[target.armv7-unknown-linux-gnueabihf.dockerfile]
file = "./Docker/Dockerfile.cross"
context = "./Docker"

[target.armv7-unknown-linux-gnueabihf.dockerfile.build-args]
LINKER_PACKAGE = "gcc-arm-linux-gnueabihf"
RUST_TARGET_TRIPLE = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = ["CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc"]
