FROM rust

ARG CROSS_DEB_ARCH
ARG LINKER_PACKAGE
ARG RUST_TARGET_TRIPLE

RUN dpkg --add-architecture $CROSS_DEB_ARCH
RUN apt-get update && apt-get install --assume-yes $LINKER_PACKAGE
RUN rustup target add $RUST_TARGET_TRIPLE

